version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydatabase
    volumes:
      - .:/app  # Mounts the entire project
      - /app/node_modules  # Avoids conflicts with node_modules inside the container
    command: npm run dev
    restart: always

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
     

volumes:
  mongodb_data:
