version: '3.8'

services:
  fastapi:
    build: .
    container_name: ai-service-fastapi
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./logs:/app/logs   
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - ai_service_network

networks:
  ai_service_network:
    driver: bridge
